### ISSUE TITLE
Missing support to environment variables

### ISSUE THREAD

**Issue by JorTurFer** [docker/aci-integration-beta#11]
Hi,
I don't know if this is a bug or a not supported feature but when I try to deploy an example compose file for a wordpress the system can't start. The problem is that the ACI doesn't set any environment variable:

![image](https://user-images.githubusercontent.com/36899226/86043428-08214b00-ba49-11ea-9e10-b2362783e376.png)

I used this yml to deploy the aci:

```yml
version: '3.4'

services:
   db:
     image: mysql:5.7
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "80:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
```

Is this feature in the roadmap?
